export const GAME_SETTINGS = {
  INITIAL_GAME_SPEED: 12,
  JUMP_SPEED: 1550,
  GRAVITY: 5000,
  RESPAWN_TIME: 0,
  ON_GROUND_POSITION: 30,
  SCORE_UPDATE_DELAY: 1000 / 10,
  GAME_SPEED_INCREMENT: 0.005,
  OBSTACLE_DISTANCE_MIN: 500,
  OBSTACLE_DISTANCE_MAX: 1000
};

export const SOUND_CONFIG = {
  JUMP: { volume: 0.2 },
  HIT: { volume: 0.2 },
  REACH: { volume: 0.2 }
};
